CREATE DATABASE IF NOT EXISTS CAREERTRACK_DB;
CREATE WAREHOUSE IF NOT EXISTS CAREERTRACK_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE DATABASE CAREERTRACK_DB;
CREATE SCHEMA IF NOT EXISTS APP;
USE SCHEMA APP;

CREATE TABLE IF NOT EXISTS USERS (
    ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS JOB_APPLICATIONS (
    ID VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    COMPANY VARCHAR(200) NOT NULL,
    JOB_TITLE VARCHAR(200) NOT NULL,
    JOB_LOCATION VARCHAR(200),
    JOB_URL VARCHAR(1000),
    STATUS VARCHAR(50) NOT NULL DEFAULT 'Saved',
    SALARY_RANGE VARCHAR(100),
    APPLIED_DATE DATE,
    DEADLINE_DATE DATE,
    NOTES VARCHAR(5000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS INTERVIEWS (
    ID VARCHAR(36) NOT NULL,
    APPLICATION_ID VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    INTERVIEW_TYPE VARCHAR(150) NOT NULL,
    SCHEDULED_AT TIMESTAMP_NTZ,
    INTERVIEWER_NAME VARCHAR(200),
    OUTCOME VARCHAR(200),
    NOTES VARCHAR(5000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (APPLICATION_ID) REFERENCES JOB_APPLICATIONS(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS APPLICATION_ACTIVITY (
    ID VARCHAR(36) NOT NULL,
    APPLICATION_ID VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    OLD_STATUS VARCHAR(50),
    NEW_STATUS VARCHAR(50),
    NOTE VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (APPLICATION_ID) REFERENCES JOB_APPLICATIONS(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
